import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {AppState,FlatList,Image,KeyboardAvoidingView,Platform,Pressable,RefreshControl,StyleSheet,Text,View} from 'react-native';
import {router,useFocusEffect,useLocalSearchParams} from 'expo-router';
import {api,profilePhoto} from '@/src/lib/api';
import {Body,Button,Input,Loading,Screen} from '@/src/components/UI';
import {useAppTheme} from '@/src/context/Theme';
import {useAuth} from '@/src/context/Auth';
import AsyncStorage from '@react-native-async-storage/async-storage';

type Message={id:string;senderUid:string;text:string;createdAt?:string|null;pending?:boolean;failed?:boolean};
type Other={uid:string;firstName?:string;authenticityScore?:number;compatibilityScore?:number};
type Messaging={unlimited:boolean;freeLimit:number;sentCount:number;remaining:number|null;locked:boolean;contactDetailSharing?:boolean};
type Conversation={matchId:string;other:Other;messages:Message[];messaging:Messaging};

const QUICK_REPLIES=['Hi! Nice to meet you','How has your day been?','What made you smile today?'];
function dayLabel(value?:string|null){if(!value)return '';const d=new Date(value);const today=new Date();const yesterday=new Date();yesterday.setDate(today.getDate()-1);if(d.toDateString()===today.toDateString())return 'Today';if(d.toDateString()===yesterday.toDateString())return 'Yesterday';return d.toLocaleDateString([],{day:'numeric',month:'short',year:d.getFullYear()===today.getFullYear()?undefined:'numeric'});}

export default function Chat(){
 const params=useLocalSearchParams<{matchId:string|string[]}>();const matchId=Array.isArray(params.matchId)?params.matchId[0]:params.matchId;
 const {colors}=useAppTheme();const {user}=useAuth();
 const [data,setData]=useState<Conversation|null>(null),[value,setValue]=useState(''),[err,setErr]=useState(''),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[sending,setSending]=useState(false);
 const list=useRef<FlatList<{message:Message;showDay:boolean}>>(null);const mounted=useRef(true);
 const load=useCallback(async(silent=false)=>{if(!matchId)return;try{if(!silent)setErr('');const next=await api<Conversation>(`/api/messages?matchId=${encodeURIComponent(matchId)}`);if(mounted.current)setData(next)}catch(e){if(!silent&&mounted.current)setErr(e instanceof Error?e.message:'Unable to load messages')}finally{if(mounted.current){setLoading(false);setRefreshing(false)}}},[matchId]);
 useEffect(()=>()=>{mounted.current=false},[]);
 useFocusEffect(useCallback(()=>{mounted.current=true;void load();const timer=setInterval(()=>{if(AppState.currentState==='active')void load(true)},5000);return()=>clearInterval(timer)},[load]));
 useEffect(()=>{if(matchId&&data)void AsyncStorage.setItem(`autoface:last-opened:${matchId}`,new Date().toISOString())},[matchId,data?.messages?.length]);
 const messages=data?.messages??[];
 const rendered=useMemo(()=>messages.map((m,i)=>({message:m,showDay:i===0||dayLabel(messages[i-1]?.createdAt)!==dayLabel(m.createdAt)})),[messages]);
 async function refresh(){setRefreshing(true);await load()}
 async function send(prefill?:string){const text=(prefill??value).trim();if(!text||!matchId||sending||data?.messaging.locked)return;const tempId=`pending-${Date.now()}`;const optimistic:Message={id:tempId,senderUid:user?.uid??'',text,createdAt:new Date().toISOString(),pending:true};setData(current=>current?{...current,messages:[...current.messages,optimistic]}:current);setValue('');setTimeout(()=>list.current?.scrollToEnd({animated:true}),30);try{setSending(true);setErr('');await api('/api/messages',{method:'POST',body:JSON.stringify({matchId,text,message:text})});await load(true)}catch(e){const raw=e instanceof Error?e.message:'Unable to send';setData(current=>current?{...current,messages:current.messages.map(m=>m.id===tempId?{...m,pending:false,failed:true}:m)}:current);setErr(raw==='MESSAGE_LIMIT_REACHED'?'You have used your free message allowance. You can still read this conversation.':raw==='CONTACT_DETAILS_MEMBERSHIP_REQUIRED'?'Contact details can be shared once messaging is unlocked.':raw)}finally{setSending(false)}}
 if(loading)return <Screen eyebrow="PRIVATE CONNECTION" title="Conversation"><Loading/></Screen>;
 return <Screen eyebrow="PRIVATE CONNECTION" title={data?.other?.firstName?`Chat with ${data.other.firstName}`:'Conversation'}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':undefined} keyboardVerticalOffset={8}>
  <Pressable onPress={()=>router.back()} hitSlop={10}><Text style={[s.back,{color:colors.blue}]}>{'< Back'}</Text></Pressable>
  {data?<View style={[s.person,{borderColor:colors.line,backgroundColor:colors.card}]}><Image source={{uri:profilePhoto(data.other.uid)}} style={[s.avatar,{backgroundColor:colors.photo}]}/><View style={s.personCopy}><Text style={[s.personName,{color:colors.text}]}>{data.other.firstName||'Your connection'}</Text><Text style={[s.small,{color:colors.muted}]}>Mutual introduction · private conversation</Text></View></View>:null}
  {data?<View style={[s.trust,{borderColor:colors.line,backgroundColor:colors.card}]}><View><Text style={[s.trustValue,{color:colors.ink}]}>{data.other.authenticityScore??'-'}%</Text><Text style={[s.small,{color:colors.muted}]}>Authenticity</Text></View><View><Text style={[s.trustValue,{color:colors.ink}]}>{data.other.compatibilityScore??'-'}%</Text><Text style={[s.small,{color:colors.muted}]}>Compatibility</Text></View><View style={s.entitlement}><Text style={[s.small,{color:data.messaging.locked?colors.rose:colors.green}]}>{data.messaging.unlimited?'Unlimited chat':data.messaging.locked?'Messaging paused':`${data.messaging.remaining??0} free left`}</Text></View></View>:null}
  {err?<View style={[s.errorBox,{borderColor:colors.line,backgroundColor:colors.card}]}><Text style={[s.error,{color:colors.rose}]}>{err}</Text><Pressable onPress={()=>void load()}><Text style={{color:colors.blue,fontWeight:'800'}}>Retry</Text></Pressable></View>:null}
  <FlatList ref={list} data={rendered} keyExtractor={(x)=>x.message.id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>} contentContainerStyle={s.list} keyboardShouldPersistTaps="handled" onContentSizeChange={()=>list.current?.scrollToEnd({animated:false})} ListEmptyComponent={<View style={s.empty}><Body>You both chose to be introduced. A simple hello is enough.</Body><View style={s.quickWrap}>{QUICK_REPLIES.map(x=><Pressable key={x} onPress={()=>void send(x)} style={[s.quick,{borderColor:colors.line,backgroundColor:colors.card}]}><Text style={{color:colors.text,fontWeight:'700'}}>{x}</Text></Pressable>)}</View></View>} renderItem={({item})=>{const m=item.message;const mine=m.senderUid===user?.uid;return <View>{item.showDay&&m.createdAt?<View style={s.day}><Text style={[s.dayText,{color:colors.muted,backgroundColor:colors.bg}]}>{dayLabel(m.createdAt)}</Text></View>:null}<View style={[s.messageRow,mine?s.mine:s.theirs]}><View style={[s.bubble,{opacity:m.failed?.65:1,backgroundColor:mine?colors.blue:colors.card,borderColor:m.failed?colors.rose:(mine?colors.blue:colors.line)}]}><Text style={[s.message,{color:mine?'#fff':colors.text}]}>{m.text}</Text><View style={s.meta}>{m.createdAt?<Text style={[s.time,{color:mine?'#DBEAFE':colors.muted}]}>{new Date(m.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</Text>:null}{mine?<Text style={[s.time,{color:m.failed?'#FECACA':'#DBEAFE'}]}>{m.failed?'Failed':m.pending?'Sending...':'Sent'}</Text>:null}</View></View></View></View>}}/>
  {data?.messaging.locked?<View style={[s.locked,{backgroundColor:colors.card,borderColor:colors.line}]}><Body>Messaging is paused. Your conversation remains available to read.</Body></View>:<View><View style={s.composer}><Input style={s.input} value={value} onChangeText={setValue} placeholder="Write a message..." multiline maxLength={1000}/><View style={s.send}><Button title={sending?'Sending...':'Send'} disabled={sending||!value.trim()} onPress={()=>void send()}/></View></View><Text style={[s.counter,{color:value.length>900?colors.rose:colors.muted}]}>{value.length}/1000</Text></View>}
 </KeyboardAvoidingView></Screen>}
const s=StyleSheet.create({flex:{flex:1,gap:8},back:{fontSize:16,fontWeight:'700'},person:{borderWidth:1,borderRadius:16,padding:10,flexDirection:'row',alignItems:'center',gap:11},avatar:{width:46,height:46,borderRadius:23},personCopy:{flex:1},personName:{fontSize:17,fontWeight:'800'},trust:{borderWidth:1,borderRadius:16,padding:10,flexDirection:'row',alignItems:'center',gap:20},trustValue:{fontSize:17,fontWeight:'800'},small:{fontSize:11},entitlement:{marginLeft:'auto'},errorBox:{borderWidth:1,borderRadius:12,padding:10,flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10},error:{fontSize:13,lineHeight:18,flex:1},list:{paddingVertical:8,gap:5,flexGrow:1},empty:{paddingVertical:28,gap:14},quickWrap:{gap:8},quick:{borderWidth:1,borderRadius:999,paddingVertical:9,paddingHorizontal:13,alignSelf:'flex-start'},day:{alignItems:'center',marginVertical:8},dayText:{fontSize:11,fontWeight:'700',paddingHorizontal:8},messageRow:{flexDirection:'row'},mine:{justifyContent:'flex-end'},theirs:{justifyContent:'flex-start'},bubble:{maxWidth:'82%',borderWidth:1,borderRadius:18,paddingHorizontal:14,paddingVertical:10},message:{fontSize:16,lineHeight:21},meta:{flexDirection:'row',justifyContent:'flex-end',gap:7,marginTop:4},time:{fontSize:10},composer:{flexDirection:'row',gap:8,alignItems:'flex-end',paddingTop:4},input:{flex:1,minHeight:48,maxHeight:110},send:{width:88},counter:{fontSize:10,textAlign:'right',marginTop:2,marginRight:96},locked:{borderWidth:1,borderRadius:14,padding:12}});
